### ISSUE TITLE
Name of this repository

### ISSUE THREAD

**Issue by meyerdan** [camunda-community-hub/camunda-8-process-solution-template#3]
I am wondering whether "Process solution" is the right name for this repository. Why did you pick it?

**Comment by falko** [comment]
That's how Bernd calls process applications in his new book ;-)

**Comment by falko** [comment]
The term process solution is also used in the docs and best practices.

![](https://docs.camunda.io/assets/images/ComponentsAndArchitecture_SaaS-edd9396b71911e6e4df0e16fa905e869.png)

So unless there is no fundamental issue or a better suggestion, I don't see a need to change anything ;-)
